name: github pages
on:
  workflow_dispatch:
  push:
    branches:
    - main # default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: true

    - name: Build
      run: pnpm build

    - name: Deploy
      run: pnpm deploy
